name: ULTIMATE RDP OPENGL DX TAILSCALE v2

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:

    - name: Create user
      run: |
        net user gamer Passw0rd! /add
        net localgroup administrators gamer /add

    - name: Enable RDP
      run: |
        reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable WARP DirectX
      run: |
        reg add HKLM\SOFTWARE\Microsoft\Direct3D /v UseWARP /t REG_DWORD /d 1 /f

    - name: Install VC++
      run: choco install vcredist-all -y || exit 0

    - name: Install DirectX
      run: choco install directx -y || exit 0

    - name: Install Mesa OpenGL
      run: choco install mesa -y || exit 0

    - name: Force software renderer
      run: |
        setx PANDA3D_FORCE_SOFTWARE 1
        setx LIBGL_ALWAYS_SOFTWARE 1

    - name: Install Tailscale
      run: choco install tailscale -y

    - name: Start Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey tskey-auth-ktMWauDQ3C11CNTRL-ptdTQ92Xh8Z9dpKLggXh7ZoaLVsy8Ui8V --hostname githubrdp

    - name: Disable sleep
      run: |
        powercfg -change -standby-timeout-ac 0
        powercfg -change -monitor-timeout-ac 0

    - name: Keep alive
      run: |
        while ($true) { Start-Sleep 60 }
