name: RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Enable RDP
        run: |
          net user runner Pass123! /add
          net localgroup administrators runner /add
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Install Tailscale
        run: |
          choco install tailscale -y

      - name: Login Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey tskey-auth-kLeYKLhXuS11CNTRL-2rN4YKdTmchBdCiNityXchSocgRRLmLuW --accept-dns=false --reset

      - name: Show IP
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4

      - name: Keep Alive
        run: |
          ping localhost -t
